name: condor_cli
description: 符号表上传辅助工具CLI.
version: 0.0.3
repository: https://github.com/LinXunFeng/condor

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  cli_completion: ^0.4.0
  http: ^1.1.0
  io: ^1.0.4
  json_annotation: ^4.8.1
  meta: ^1.9.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  # flutter pub run build_runner build
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0

executables:
  condor:
