name: condor_cli
description: 符号表上传辅助工具CLI.
version: 0.0.1
repository: https://github.com/LinXunFeng/condor

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.4.2
  meta: ^1.9.0
  io: ^1.0.4
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  flutter_archive: ^6.0.0
  cli_completion: ^0.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  # flutter pub run build_runner build
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

executables:
  condor:
