name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            artifact_prefix: macos
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Get dependencies
        run: |
          cd packages/condor_cli/
          dart pub get

      - name: Running build
        run: |
          cd packages/condor_cli/
          mkdir -p bin/${{ matrix.target }}
          dart compile exe bin/condor.dart -o bin/${{ matrix.target }}/condor

      - name: Packaging final binary
        shell: bash
        run: |
          cd packages/condor_cli/bin/${{ matrix.target }}
          tar czvf condor-${{ matrix.artifact_prefix }}.tar.gz condor
          shasum -a 256 condor-${{ matrix.artifact_prefix }}.tar.gz > condor-${{ matrix.artifact_prefix }}.sha256

      - name: Releasing assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/condor_cli/bin/${{ matrix.target }}/condor-${{ matrix.artifact_prefix }}.tar.gz
            packages/condor_cli/bin/${{ matrix.target }}/condor-${{ matrix.artifact_prefix }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: sha256-${{ strategy.job-index }}
          path: packages/condor_cli/bin/${{ matrix.target }}/condor-${{ matrix.artifact_prefix }}.sha256

  update:
    name: Update Homebrew tap
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          pattern: sha256-*
          merge-multiple: true

      # GitHub Apps
      - name: Generate github apps token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CONDOR_APP_ID }}
          private-key: ${{ secrets.CONDOR_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - id: version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - id: checksum
        shell: bash
        run: |
          echo "sha256_macos=$(cat condor-macos.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: LinXunFeng/homebrew-tap
          event-type: update-tap
          client-payload: '{ "sha256_macos": "${{ steps.checksum.outputs.sha256_macos }}", "version": "${{ steps.version.outputs.version }}" }'
